name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: [3.6, 3.7, 3.8]
          services: [release, lowest]
          include:
            - services: release
              SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://invenio:invenio@localhost:5432/invenio"
              POSTGRESQL_VERSION: POSTGRESQL_12_LATEST
              ES_VERSION: "ES_7_LATEST"
              EXTRAS: "all,postgresql,elasticsearch7"
              REQUIREMENTS: "release"
              REQUIREMENTS_LEVEL: "pypi"
            - services: lowest
              SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://invenio:invenio@localhost:5432/invenio"
              POSTGRESQL_VERSION: POSTGRESQL_9_LATEST
              ES_VERSION: "ES_7_LATEST"
              EXTRAS: "all,postgresql,elasticsearch7"
              REQUIREMENTS: "lowest"
              REQUIREMENTS_LEVEL: "min"
    
    env:
      SQLALCHEMY_DATABASE_URI: ${{matrix.SQLALCHEMY_DATABASE_URI}}
      POSTGRESQL_VERSION: ${{matrix.POSTGRESQL_VERSION}}
      ES_VERSION: ${{matrix.ES_VERSION}}
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate dependencies
        run: |
          python -m pip install --upgrade pip setuptools py wheel requirements-builder
          requirements-builder -e ${{ matrix.EXTRAS }}  --level=${{ matrix.REQUIREMENTS_LEVEL }} setup.py > .${{ matrix.REQUIREMENTS_LEVEL }}-${{ matrix.python-version }}-requirements.txt

      - name: Install dependencies
        run: |
          pip install -r .${{matrix.REQUIREMENTS_LEVEL}}-${{ matrix.python-version }}-requirements.txt
          pip install .[all]
          pip freeze
          docker --version
          docker-compose --version

      - name: Run tests
        run: |
          ./run-tests.sh 
